spring:
  application:
    name: patient-ms
  webflux:
    base-path: /patient-ms
  flyway:
    enabled: true
    url: ${FLYWAY_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/patient?createDatabaseIfNotExist=true}
    user: ${DB_USERNAME:jasho}
    password: ${DB_PASSWORD:password}
  r2dbc:
    url: ${R2DBC_URL:r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/patient}
    username: ${DB_USERNAME:jasho}
    password: ${DB_PASSWORD:password}

server:
  port: ${SERVER_PORT:8124}

management:
  endpoints:
    web:
      exposure:
        include: health,info
